[package]
name = "cedar-evaluation"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
cedar-policy = "2.0.1"
serde_json = "1.0"
actix-web = "4.3.1"
serde = { version = "1.0", features = ["derive"] }
